import Image from 'next/image'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center p-24">
      <h1 className="text-4xl font-bold text-center p-2">Home</h1>
      <p className="p-2">
        This is a really long sentence a lot like that Ipsum Lorem stuff, but I don't speak latin so you've got this jumble of words instead.
      </p>
      <p className="p-2">
        Some more really long sentences, this time generated by GitHub copilot: 
        The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. Wow, how imaganitive.
      </p>

    </main>
  )
}
